### PR TITLE
Branch general

### PR DESCRIPTION
**Pull request by JohnGolgota**
- [ ] pero

### CODE REVIEW

**Review by DuvanArwenLazar — APPROVED** [review]
no

**Comment by Kolozuz** [comment]
approved

**Review by Kolozuz — APPROVED** [review]
approved babe

**Comment by DuvanArwenLazar** [comment]
no

**Review by Kolozuz — APPROVED** [review]
si apruebo ombe

**Comment by Kolozuz** [comment]
#29 sucks

**Pull request merged**
